apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: portal-go-canary-app 
  labels:
    app: portalgocanaryapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portalgocanaryapp
  template:
    metadata:
      labels:
        app: portalgocanaryapp 
    spec:
      containers:
        - name: portalgocanaryapp 
          image: ronacr.azurecr.io/portalgocanaryapp
          ports:
          - containerPort: 80
