apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: portalreviewapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portalreviewapp 
    spec:
      containers:
        - name: portalreviewapp 
          image: ronacr.azurecr.io/portalreviewapp
          ports:
          - containerPort: 80