apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: portalgocanaryapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portalgocanaryapp 
    spec:
      containers:
        - name: portalgocanaryapp 
          image: ronacr.azurecr.io/portalgocanaryapp
          ports:
          - containerPort: 80